// AUTO-GENERATED by scripts/gen-prebuilt-ssr.mjs from src/app5.js — do not edit by hand.
// Used by [[catchall]].js to server-render /screeners/* pages for SEO.
export const PREBUILT_SCREENS_SSR = [
 {
  "slug": "undervalued-stocks",
  "name": "Undervalued Stocks",
  "cat": "Value & Undervalued",
  "desc": "Profitable companies trading at low earnings and book multiples.",
  "q": "P/E > 0 AND P/E < 15 AND P/B < 2 AND ROE > 10 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 15
   },
   {
    "metric": "pb",
    "op": "<",
    "value": 2
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 10
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "low-pe-stocks",
  "name": "Low PE Stocks",
  "cat": "Value & Undervalued",
  "desc": "Stocks priced below 12x earnings.",
  "q": "P/E > 0 AND P/E < 12 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 12
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "low-pb-stocks",
  "name": "Low PB Stocks",
  "cat": "Value & Undervalued",
  "desc": "Stocks trading below book value.",
  "q": "P/B > 0 AND P/B < 1 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "pb",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pb",
    "op": "<",
    "value": 1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "cheap-stocks-to-buy-now",
  "name": "Cheap Stocks To Buy Now",
  "cat": "Value & Undervalued",
  "desc": "Low-multiple stocks that are still profitable and lightly leveraged.",
  "q": "P/E > 0 AND P/E < 12 AND ROE > 12 AND Debt to Equity < 1 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 12
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 12
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "best-value-stocks",
  "name": "Best Value Stocks",
  "cat": "Value & Undervalued",
  "desc": "High earnings yield plus solid returns on equity.",
  "q": "P/E > 0 AND P/E < 15 AND Earnings yield > 7 AND ROE > 12 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 15
   },
   {
    "metric": "earningsYield",
    "op": ">",
    "value": 7
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 12
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "undervalued-growth-stocks",
  "name": "Undervalued Growth Stocks",
  "cat": "Value & Undervalued",
  "desc": "Growing companies with PEG below 1 — growth cheaper than it looks.",
  "q": "PEG Ratio > 0 AND PEG Ratio < 1 AND Sales growth > 10 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "peg",
    "op": ">",
    "value": 0
   },
   {
    "metric": "peg",
    "op": "<",
    "value": 1
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 10
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "stocks-below-intrinsic-value",
  "name": "Stocks Below Intrinsic Value",
  "cat": "Value & Undervalued",
  "desc": "Cheap on both earnings and free cash flow.",
  "q": "P/E > 0 AND P/E < 12 AND Price to Free Cash Flow > 0 AND Price to Free Cash Flow < 15 AND ROE > 10",
  "conditions": [
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 12
   },
   {
    "metric": "priceToFreeCashFlow",
    "op": ">",
    "value": 0
   },
   {
    "metric": "priceToFreeCashFlow",
    "op": "<",
    "value": 15
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 10
   }
  ]
 },
 {
  "slug": "low-peg-ratio-stocks",
  "name": "Low PEG Ratio Stocks",
  "cat": "Value & Undervalued",
  "desc": "Growth-adjusted valuation below 1.",
  "q": "PEG Ratio > 0 AND PEG Ratio < 1 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "peg",
    "op": ">",
    "value": 0
   },
   {
    "metric": "peg",
    "op": "<",
    "value": 1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "undervalued-large-cap-stocks",
  "name": "Undervalued Large Cap Stocks",
  "cat": "Value & Undervalued",
  "desc": "Large caps under 15x earnings with healthy ROE.",
  "q": "Market Cap > 10000 AND P/E > 0 AND P/E < 15 AND ROE > 12",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 10000000000
   },
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 15
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 12
   }
  ]
 },
 {
  "slug": "undervalued-dividend-stocks",
  "name": "Undervalued Dividend Stocks",
  "cat": "Value & Undervalued",
  "desc": "Cheap stocks that also pay a meaningful dividend.",
  "q": "Dividend Yield > 2.5 AND P/E > 0 AND P/E < 15 AND ROE > 10 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 2.5
   },
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 15
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 10
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "growth-stocks",
  "name": "Growth Stocks",
  "cat": "Growth",
  "desc": "Double-digit sales and profit growth.",
  "q": "Sales growth > 15 AND Profit growth > 15 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "profitGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "high-growth-stocks",
  "name": "High Growth Stocks",
  "cat": "Growth",
  "desc": "Sustained 20%+ growth over three years.",
  "q": "Sales growth 3Years > 20 AND Profit growth 3Years > 20 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "salesGrowth3y",
    "op": ">",
    "value": 20
   },
   {
    "metric": "profitGrowth3y",
    "op": ">",
    "value": 20
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "best-growth-stocks-to-buy",
  "name": "Best Growth Stocks To Buy",
  "cat": "Growth",
  "desc": "Multi-year growers with high margins and strong ROE.",
  "q": "Sales growth 3Years > 15 AND ROE > 15 AND Gross Margin > 40 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "salesGrowth3y",
    "op": ">",
    "value": 15
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 15
   },
   {
    "metric": "grossMargin",
    "op": ">",
    "value": 40
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "small-cap-growth-stocks",
  "name": "Small Cap Growth Stocks",
  "cat": "Growth",
  "desc": "Small companies ($300M–$2B) growing fast.",
  "q": "Market Cap > 300 AND Market Cap < 2000 AND Sales growth > 15 AND Profit growth > 10",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 300000000
   },
   {
    "metric": "marketCap",
    "op": "<",
    "value": 2000000000
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "profitGrowth",
    "op": ">",
    "value": 10
   }
  ]
 },
 {
  "slug": "growth-technology-stocks",
  "name": "Growth Technology Stocks",
  "cat": "Growth",
  "desc": "Technology companies with 15%+ revenue growth.",
  "q": "Sector = Technology AND Sales growth > 15 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Technology"
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "high-revenue-growth-stocks",
  "name": "High Revenue Growth Stocks",
  "cat": "Growth",
  "desc": "Revenue growing above 25% a year.",
  "q": "Sales growth > 25 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 25
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "high-eps-growth-stocks",
  "name": "High EPS Growth Stocks",
  "cat": "Growth",
  "desc": "Profitable companies compounding earnings above 25%.",
  "q": "Profit growth > 25 AND EPS > 0 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "profitGrowth",
    "op": ">",
    "value": 25
   },
   {
    "metric": "eps",
    "op": ">",
    "value": 0
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "aggressive-small-caps",
  "name": "Aggressive Small Caps",
  "cat": "Growth",
  "desc": "Small caps with accelerating quarterly sales.",
  "q": "Market Cap > 300 AND Market Cap < 2000 AND YOY Qtr sales growth > 25 AND Sales growth > 20",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 300000000
   },
   {
    "metric": "marketCap",
    "op": "<",
    "value": 2000000000
   },
   {
    "metric": "yoyQuarterlySalesGrowth",
    "op": ">",
    "value": 25
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 20
   }
  ]
 },
 {
  "slug": "mid-cap-growth-stocks",
  "name": "Mid Cap Growth Stocks",
  "cat": "Growth",
  "desc": "Mid caps ($2B–$10B) with double-digit growth.",
  "q": "Market Cap > 2000 AND Market Cap < 10000 AND Sales growth > 15 AND Profit growth > 10",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   },
   {
    "metric": "marketCap",
    "op": "<",
    "value": 10000000000
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "profitGrowth",
    "op": ">",
    "value": 10
   }
  ]
 },
 {
  "slug": "fastest-growing-stocks",
  "name": "Fastest Growing Stocks",
  "cat": "Growth",
  "desc": "30%+ sales and profit growth in the latest quarter.",
  "q": "YOY Qtr sales growth > 30 AND YOY Qtr profit growth > 30 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "yoyQuarterlySalesGrowth",
    "op": ">",
    "value": 30
   },
   {
    "metric": "yoyQuarterlyProfitGrowth",
    "op": ">",
    "value": 30
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "high-dividend-stocks",
  "name": "High Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "Yields above 4% from established companies.",
  "q": "Dividend Yield > 4 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 4
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "dividend-stocks",
  "name": "Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "All dividend payers above $1B market cap.",
  "q": "Dividend Yield > 1 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "best-dividend-stocks",
  "name": "Best Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "Well-covered dividends from profitable, low-debt large caps.",
  "q": "Dividend Yield > 2.5 AND ROE > 12 AND Debt to Equity < 1 AND Interest Coverage Ratio > 4 AND Market Cap > 5000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 2.5
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 12
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 1
   },
   {
    "metric": "interestCoverage",
    "op": ">",
    "value": 4
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 5000000000
   }
  ]
 },
 {
  "slug": "dividend-aristocrats",
  "name": "Dividend Aristocrats",
  "cat": "Dividend & Income",
  "desc": "Aristocrat-style profile: large, consistently profitable payers.",
  "q": "Dividend Yield > 2 AND Average ROE 5Years > 12 AND Net Margin > 10 AND Market Cap > 10000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 2
   },
   {
    "metric": "avgRoe5y",
    "op": ">",
    "value": 12
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 10
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 10000000000
   }
  ]
 },
 {
  "slug": "dividend-kings",
  "name": "Dividend Kings",
  "cat": "Dividend & Income",
  "desc": "King-style profile: very large, high-quality, conservatively financed payers.",
  "q": "Dividend Yield > 2 AND Average ROE 5Years > 15 AND Debt to Equity < 1 AND Market Cap > 20000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 2
   },
   {
    "metric": "avgRoe5y",
    "op": ">",
    "value": 15
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 20000000000
   }
  ]
 },
 {
  "slug": "monthly-dividend-stocks",
  "name": "Monthly Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "High-yield REITs — where most monthly payers live.",
  "q": "Sector = Real Estate AND Dividend Yield > 3 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Real Estate"
   },
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 3
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "high-yield-dividend-stocks",
  "name": "High Yield Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "Yields above 6% — check payout sustainability.",
  "q": "Dividend Yield > 6 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 6
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "safe-dividend-stocks",
  "name": "Safe Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "Moderate yields backed by low debt and strong interest coverage.",
  "q": "Dividend Yield > 2 AND Dividend Yield < 6 AND Debt to Equity < 0.8 AND Interest Coverage Ratio > 5 AND Net Margin > 8 AND Market Cap > 5000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 2
   },
   {
    "metric": "dividendYield",
    "op": "<",
    "value": 6
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 0.8
   },
   {
    "metric": "interestCoverage",
    "op": ">",
    "value": 5
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 8
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 5000000000
   }
  ]
 },
 {
  "slug": "dividend-growth-stocks",
  "name": "Dividend Growth Stocks",
  "cat": "Dividend & Income",
  "desc": "Payers growing profits fast enough to keep raising the dividend.",
  "q": "Dividend Yield > 1.5 AND Profit growth 5Years > 8 AND ROE > 15 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 1.5
   },
   {
    "metric": "profitGrowth5y",
    "op": ">",
    "value": 8
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 15
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "reit-dividend-stocks",
  "name": "REIT Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "Real estate trusts yielding above 4%.",
  "q": "Sector = Real Estate AND Dividend Yield > 4 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Real Estate"
   },
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 4
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "dividend-stocks-under-5",
  "name": "Dividend Stocks Under $5",
  "cat": "Dividend & Income",
  "desc": "Sub-$5 stocks that still pay a dividend.",
  "q": "Price < 5 AND Price > 0.5 AND Dividend Yield > 3",
  "conditions": [
   {
    "metric": "price",
    "op": "<",
    "value": 5
   },
   {
    "metric": "price",
    "op": ">",
    "value": 0.5
   },
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 3
   }
  ]
 },
 {
  "slug": "dividend-stocks-under-10",
  "name": "Dividend Stocks Under $10",
  "cat": "Dividend & Income",
  "desc": "Sub-$10 stocks yielding above 3%.",
  "q": "Price < 10 AND Price > 1 AND Dividend Yield > 3",
  "conditions": [
   {
    "metric": "price",
    "op": "<",
    "value": 10
   },
   {
    "metric": "price",
    "op": ">",
    "value": 1
   },
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 3
   }
  ]
 },
 {
  "slug": "low-debt-dividend-stocks",
  "name": "Low Debt Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "Dividend payers with debt-to-equity below 0.5.",
  "q": "Dividend Yield > 2.5 AND Debt to Equity < 0.5 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 2.5
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 0.5
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "dividend-payout-ratio-stocks",
  "name": "Dividend Payout Ratio Stocks",
  "cat": "Dividend & Income",
  "desc": "Payers whose earnings comfortably cover the dividend.",
  "q": "Dividend Yield > 2 AND Net Margin > 10 AND EPS > 1 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 2
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 10
   },
   {
    "metric": "eps",
    "op": ">",
    "value": 1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "blue-chip-dividend-stocks",
  "name": "Blue Chip Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "$50B+ companies that pay above 2%.",
  "q": "Market Cap > 50000 AND Dividend Yield > 2",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 50000000000
   },
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 2
   }
  ]
 },
 {
  "slug": "s-p-500-dividend-stocks",
  "name": "S&P 500 Dividend Stocks",
  "cat": "Dividend & Income",
  "desc": "S&P-scale large caps that pay dividends.",
  "q": "Market Cap > 15000 AND Dividend Yield > 1.5",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 15000000000
   },
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 1.5
   }
  ]
 },
 {
  "slug": "high-roe-stocks",
  "name": "High ROE Stocks",
  "cat": "Quality & Profitability",
  "desc": "Return on equity above 20%.",
  "q": "ROE > 20 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "roe",
    "op": ">",
    "value": 20
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "quality-stocks",
  "name": "Quality Stocks",
  "cat": "Quality & Profitability",
  "desc": "High returns on capital, real margins, manageable debt.",
  "q": "ROE > 15 AND ROCE > 15 AND Net Margin > 10 AND Debt to Equity < 1 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "roe",
    "op": ">",
    "value": 15
   },
   {
    "metric": "roce",
    "op": ">",
    "value": 15
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 10
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "wide-moat-stocks",
  "name": "Wide Moat Stocks",
  "cat": "Quality & Profitability",
  "desc": "Fat gross margins and years of consistently high ROE — moat behavior.",
  "q": "Gross Margin > 50 AND Net Margin > 15 AND Average ROE 5Years > 15 AND Market Cap > 10000",
  "conditions": [
   {
    "metric": "grossMargin",
    "op": ">",
    "value": 50
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 15
   },
   {
    "metric": "avgRoe5y",
    "op": ">",
    "value": 15
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 10000000000
   }
  ]
 },
 {
  "slug": "low-debt-stocks",
  "name": "Low Debt Stocks",
  "cat": "Quality & Profitability",
  "desc": "Debt-to-equity below 0.3.",
  "q": "Debt to Equity < 0.3 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 0.3
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "high-profit-margin-stocks",
  "name": "High Profit Margin Stocks",
  "cat": "Quality & Profitability",
  "desc": "Net margins above 20%.",
  "q": "Net Margin > 20 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "netMargin",
    "op": ">",
    "value": 20
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "high-free-cash-flow-stocks",
  "name": "High Free Cash Flow Stocks",
  "cat": "Quality & Profitability",
  "desc": "Cheap relative to the free cash they generate.",
  "q": "Price to Free Cash Flow > 0 AND Price to Free Cash Flow < 15 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "priceToFreeCashFlow",
    "op": ">",
    "value": 0
   },
   {
    "metric": "priceToFreeCashFlow",
    "op": "<",
    "value": 15
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "strong-balance-sheet-stocks",
  "name": "Strong Balance Sheet Stocks",
  "cat": "Quality & Profitability",
  "desc": "High liquidity, low debt, strong interest coverage.",
  "q": "Current ratio > 2 AND Debt to Equity < 0.5 AND Interest Coverage Ratio > 5 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "currentRatio",
    "op": ">",
    "value": 2
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 0.5
   },
   {
    "metric": "interestCoverage",
    "op": ">",
    "value": 5
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "high-roa-stocks",
  "name": "High ROA Stocks",
  "cat": "Quality & Profitability",
  "desc": "Return on assets above 10%.",
  "q": "ROA > 10 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "roa",
    "op": ">",
    "value": 10
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "companies-with-highest-roe",
  "name": "Companies With Highest ROE",
  "cat": "Quality & Profitability",
  "desc": "The elite tier — ROE above 30%.",
  "q": "ROE > 30 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "roe",
    "op": ">",
    "value": 30
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "low-debt-high-roe-stocks",
  "name": "Low Debt High ROE Stocks",
  "cat": "Quality & Profitability",
  "desc": "High returns without leverage doing the work.",
  "q": "Debt to Equity < 0.5 AND ROE > 20 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 0.5
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 20
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "52-week-high-stocks",
  "name": "52 Week High Stocks",
  "cat": "Momentum & Technical",
  "desc": "Strong daily gainers on heavy volume — names pushing toward highs.",
  "q": "Change % > 3 AND Volume > 1000000 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "changePct",
    "op": ">",
    "value": 3
   },
   {
    "metric": "volume",
    "op": ">",
    "value": 1000000
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "stocks-near-52-week-high",
  "name": "Stocks Near 52 Week High",
  "cat": "Momentum & Technical",
  "desc": "Steady climbers with earnings momentum behind the move.",
  "q": "Change % > 0 AND YOY Qtr profit growth > 15 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "changePct",
    "op": ">",
    "value": 0
   },
   {
    "metric": "yoyQuarterlyProfitGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "52-week-low-stocks",
  "name": "52 Week Low Stocks",
  "cat": "Momentum & Technical",
  "desc": "Heavy decliners — a contrarian hunting ground.",
  "q": "Change % < -3 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "changePct",
    "op": "<",
    "value": -3
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "oversold-stocks",
  "name": "Oversold Stocks",
  "cat": "Momentum & Technical",
  "desc": "Beaten down today but still cheap and profitable.",
  "q": "Change % < -5 AND P/E > 0 AND P/E < 15",
  "conditions": [
   {
    "metric": "changePct",
    "op": "<",
    "value": -5
   },
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 15
   }
  ]
 },
 {
  "slug": "overbought-stocks",
  "name": "Overbought Stocks",
  "cat": "Momentum & Technical",
  "desc": "Sharp movers trading at stretched valuations.",
  "q": "Change % > 5 AND P/E > 40",
  "conditions": [
   {
    "metric": "changePct",
    "op": ">",
    "value": 5
   },
   {
    "metric": "pe",
    "op": ">",
    "value": 40
   }
  ]
 },
 {
  "slug": "momentum-stocks",
  "name": "Momentum Stocks",
  "cat": "Momentum & Technical",
  "desc": "Price strength confirmed by accelerating fundamentals.",
  "q": "Change % > 5 AND YOY Qtr profit growth > 20 AND YOY Qtr sales growth > 15 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "changePct",
    "op": ">",
    "value": 5
   },
   {
    "metric": "yoyQuarterlyProfitGrowth",
    "op": ">",
    "value": 20
   },
   {
    "metric": "yoyQuarterlySalesGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "breakout-stocks",
  "name": "Breakout Stocks",
  "cat": "Momentum & Technical",
  "desc": "Big moves on unusually heavy volume.",
  "q": "Change % > 4 AND Volume > 2000000 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "changePct",
    "op": ">",
    "value": 4
   },
   {
    "metric": "volume",
    "op": ">",
    "value": 2000000
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "most-active-stocks",
  "name": "Most Active Stocks",
  "cat": "Momentum & Technical",
  "desc": "Highest trading volume today.",
  "q": "Volume > 10000000",
  "conditions": [
   {
    "metric": "volume",
    "op": ">",
    "value": 10000000
   }
  ]
 },
 {
  "slug": "day-gainers-stocks",
  "name": "Day Gainers Stocks",
  "cat": "Momentum & Technical",
  "desc": "Up more than 5% today.",
  "q": "Change % > 5",
  "conditions": [
   {
    "metric": "changePct",
    "op": ">",
    "value": 5
   }
  ]
 },
 {
  "slug": "day-losers-stocks",
  "name": "Day Losers Stocks",
  "cat": "Momentum & Technical",
  "desc": "Down more than 5% today.",
  "q": "Change % < -5",
  "conditions": [
   {
    "metric": "changePct",
    "op": "<",
    "value": -5
   }
  ]
 },
 {
  "slug": "high-volume-stocks",
  "name": "High Volume Stocks",
  "cat": "Momentum & Technical",
  "desc": "Liquid names trading over 5M shares.",
  "q": "Volume > 5000000 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "volume",
    "op": ">",
    "value": 5000000
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "stocks-with-unusual-volume",
  "name": "Stocks With Unusual Volume",
  "cat": "Momentum & Technical",
  "desc": "Heavy volume paired with a strong price move.",
  "q": "Volume > 5000000 AND Change % > 3",
  "conditions": [
   {
    "metric": "volume",
    "op": ">",
    "value": 5000000
   },
   {
    "metric": "changePct",
    "op": ">",
    "value": 3
   }
  ]
 },
 {
  "slug": "penny-stocks",
  "name": "Penny Stocks",
  "cat": "Size & Price",
  "desc": "Stocks trading under $5.",
  "q": "Price < 5 AND Price > 0.1",
  "conditions": [
   {
    "metric": "price",
    "op": "<",
    "value": 5
   },
   {
    "metric": "price",
    "op": ">",
    "value": 0.1
   }
  ]
 },
 {
  "slug": "penny-stocks-to-buy",
  "name": "Penny Stocks To Buy",
  "cat": "Size & Price",
  "desc": "Sub-$5 stocks with growing sales and controlled debt.",
  "q": "Price < 5 AND Price > 0.5 AND Sales growth > 10 AND Debt to Equity < 1",
  "conditions": [
   {
    "metric": "price",
    "op": "<",
    "value": 5
   },
   {
    "metric": "price",
    "op": ">",
    "value": 0.5
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 10
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 1
   }
  ]
 },
 {
  "slug": "best-penny-stocks",
  "name": "Best Penny Stocks",
  "cat": "Size & Price",
  "desc": "Sub-$5 stocks that are actually profitable.",
  "q": "Price < 5 AND Price > 0.5 AND EPS > 0 AND ROE > 5",
  "conditions": [
   {
    "metric": "price",
    "op": "<",
    "value": 5
   },
   {
    "metric": "price",
    "op": ">",
    "value": 0.5
   },
   {
    "metric": "eps",
    "op": ">",
    "value": 0
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 5
   }
  ]
 },
 {
  "slug": "small-cap-stocks",
  "name": "Small Cap Stocks",
  "cat": "Size & Price",
  "desc": "Market cap between $300M and $2B.",
  "q": "Market Cap > 300 AND Market Cap < 2000",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 300000000
   },
   {
    "metric": "marketCap",
    "op": "<",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "large-cap-stocks",
  "name": "Large Cap Stocks",
  "cat": "Size & Price",
  "desc": "Market cap above $10B.",
  "q": "Market Cap > 10000",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 10000000000
   }
  ]
 },
 {
  "slug": "blue-chip-stocks",
  "name": "Blue Chip Stocks",
  "cat": "Size & Price",
  "desc": "$50B+ leaders with proven profitability.",
  "q": "Market Cap > 50000 AND ROE > 12 AND Net Margin > 8",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 50000000000
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 12
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 8
   }
  ]
 },
 {
  "slug": "stocks-under-5",
  "name": "Stocks Under $5",
  "cat": "Size & Price",
  "desc": "Everything under $5 with a real market cap.",
  "q": "Price < 5 AND Price > 0.1 AND Market Cap > 100",
  "conditions": [
   {
    "metric": "price",
    "op": "<",
    "value": 5
   },
   {
    "metric": "price",
    "op": ">",
    "value": 0.1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 100000000
   }
  ]
 },
 {
  "slug": "stocks-under-10",
  "name": "Stocks Under $10",
  "cat": "Size & Price",
  "desc": "Under $10 with at least $200M market cap.",
  "q": "Price < 10 AND Price > 1 AND Market Cap > 200",
  "conditions": [
   {
    "metric": "price",
    "op": "<",
    "value": 10
   },
   {
    "metric": "price",
    "op": ">",
    "value": 1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 200000000
   }
  ]
 },
 {
  "slug": "stocks-under-1",
  "name": "Stocks Under $1",
  "cat": "Size & Price",
  "desc": "The riskiest tier — trading below $1.",
  "q": "Price < 1 AND Price > 0.01",
  "conditions": [
   {
    "metric": "price",
    "op": "<",
    "value": 1
   },
   {
    "metric": "price",
    "op": ">",
    "value": 0.01
   }
  ]
 },
 {
  "slug": "mega-cap-stocks",
  "name": "Mega Cap Stocks",
  "cat": "Size & Price",
  "desc": "The giants — market cap above $200B.",
  "q": "Market Cap > 200000",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 200000000000
   }
  ]
 },
 {
  "slug": "analyst-strong-buy-stocks",
  "name": "Analyst Strong Buy Stocks",
  "cat": "Institutional & Analyst",
  "desc": "The growth-plus-quality profile analysts typically rate highest.",
  "q": "ROE > 15 AND Profit growth > 15 AND YOY Qtr profit growth > 10 AND Market Cap > 5000",
  "conditions": [
   {
    "metric": "roe",
    "op": ">",
    "value": 15
   },
   {
    "metric": "profitGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "yoyQuarterlyProfitGrowth",
    "op": ">",
    "value": 10
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 5000000000
   }
  ]
 },
 {
  "slug": "stocks-with-insider-buying",
  "name": "Stocks With Insider Buying",
  "cat": "Institutional & Analyst",
  "desc": "Cheap, profitable pullbacks — the setups insiders tend to buy.",
  "q": "P/E > 0 AND P/E < 15 AND Change % < 0 AND ROE > 10 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 15
   },
   {
    "metric": "changePct",
    "op": "<",
    "value": 0
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 10
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "most-institutionally-bought-stocks",
  "name": "Most Institutionally Bought Stocks",
  "cat": "Institutional & Analyst",
  "desc": "Large, liquid names where institutions concentrate.",
  "q": "Market Cap > 20000 AND Volume > 2000000",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 20000000000
   },
   {
    "metric": "volume",
    "op": ">",
    "value": 2000000
   }
  ]
 },
 {
  "slug": "stock-buybacks-list",
  "name": "Stock Buybacks List",
  "cat": "Institutional & Analyst",
  "desc": "Cash-generative large caps with capacity for buybacks.",
  "q": "Price to Free Cash Flow > 0 AND Price to Free Cash Flow < 20 AND Debt to Equity < 1 AND Market Cap > 10000",
  "conditions": [
   {
    "metric": "priceToFreeCashFlow",
    "op": ">",
    "value": 0
   },
   {
    "metric": "priceToFreeCashFlow",
    "op": "<",
    "value": 20
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 1
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 10000000000
   }
  ]
 },
 {
  "slug": "hedge-fund-favorite-stocks",
  "name": "Hedge Fund Favorite Stocks",
  "cat": "Institutional & Analyst",
  "desc": "High-ROE growers at hedge-fund scale.",
  "q": "Market Cap > 10000 AND ROE > 20 AND Sales growth > 10",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 10000000000
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 20
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 10
   }
  ]
 },
 {
  "slug": "stocks-warren-buffett-owns",
  "name": "Stocks Warren Buffett Owns",
  "cat": "Institutional & Analyst",
  "desc": "Buffett-style criteria: durable returns, fat margins, low debt.",
  "q": "ROE > 20 AND Average ROE 5Years > 18 AND ROCE > 15 AND Net Margin > 15 AND Debt to Equity < 0.5 AND Interest Coverage Ratio > 5 AND Market Cap > 5000",
  "conditions": [
   {
    "metric": "roe",
    "op": ">",
    "value": 20
   },
   {
    "metric": "avgRoe5y",
    "op": ">",
    "value": 18
   },
   {
    "metric": "roce",
    "op": ">",
    "value": 15
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 15
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 0.5
   },
   {
    "metric": "interestCoverage",
    "op": ">",
    "value": 5
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 5000000000
   }
  ]
 },
 {
  "slug": "recently-upgraded-stocks",
  "name": "Recently Upgraded Stocks",
  "cat": "Institutional & Analyst",
  "desc": "Earnings surprises with price follow-through — upgrade fuel.",
  "q": "YOY Qtr profit growth > 25 AND Change % > 2 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "yoyQuarterlyProfitGrowth",
    "op": ">",
    "value": 25
   },
   {
    "metric": "changePct",
    "op": ">",
    "value": 2
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "rising-institutional-ownership-stocks",
  "name": "Rising Institutional Ownership Stocks",
  "cat": "Institutional & Analyst",
  "desc": "Growing large caps with deep, liquid trading.",
  "q": "Market Cap > 5000 AND YOY Qtr sales growth > 15 AND Volume > 1000000",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 5000000000
   },
   {
    "metric": "yoyQuarterlySalesGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "volume",
    "op": ">",
    "value": 1000000
   }
  ]
 },
 {
  "slug": "most-shorted-stocks",
  "name": "Most Shorted Stocks",
  "cat": "Risk & Volatility",
  "desc": "Leveraged loss-makers — the profile short sellers target.",
  "q": "Debt to Equity > 2 AND Net Margin < 0 AND Market Cap > 500",
  "conditions": [
   {
    "metric": "debtToEquity",
    "op": ">",
    "value": 2
   },
   {
    "metric": "netMargin",
    "op": "<",
    "value": 0
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   }
  ]
 },
 {
  "slug": "high-short-interest-stocks",
  "name": "High Short Interest Stocks",
  "cat": "Risk & Volatility",
  "desc": "Unprofitable names under active selling pressure.",
  "q": "Net Margin < 0 AND Change % < -2 AND Volume > 1000000",
  "conditions": [
   {
    "metric": "netMargin",
    "op": "<",
    "value": 0
   },
   {
    "metric": "changePct",
    "op": "<",
    "value": -2
   },
   {
    "metric": "volume",
    "op": ">",
    "value": 1000000
   }
  ]
 },
 {
  "slug": "low-volatility-stocks",
  "name": "Low Volatility Stocks",
  "cat": "Risk & Volatility",
  "desc": "Beta below 0.8 — calmer than the market.",
  "q": "Beta < 0.8 AND Beta > 0 AND Market Cap > 5000",
  "conditions": [
   {
    "metric": "beta",
    "op": "<",
    "value": 0.8
   },
   {
    "metric": "beta",
    "op": ">",
    "value": 0
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 5000000000
   }
  ]
 },
 {
  "slug": "high-beta-stocks",
  "name": "High Beta Stocks",
  "cat": "Risk & Volatility",
  "desc": "Beta above 1.5 — amplified market moves.",
  "q": "Beta > 1.5 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "beta",
    "op": ">",
    "value": 1.5
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "defensive-stocks",
  "name": "Defensive Stocks",
  "cat": "Risk & Volatility",
  "desc": "Consumer staples that hold up in downturns.",
  "q": "Sector = Consumer Defensive AND Market Cap > 2000 AND Dividend Yield > 1.5",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Consumer Defensive"
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   },
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 1.5
   }
  ]
 },
 {
  "slug": "recession-proof-stocks",
  "name": "Recession Proof Stocks",
  "cat": "Risk & Volatility",
  "desc": "Low beta, real margins, and a dividend cushion.",
  "q": "Beta < 0.9 AND Beta > 0 AND Net Margin > 8 AND Dividend Yield > 2 AND Market Cap > 5000",
  "conditions": [
   {
    "metric": "beta",
    "op": "<",
    "value": 0.9
   },
   {
    "metric": "beta",
    "op": ">",
    "value": 0
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 8
   },
   {
    "metric": "dividendYield",
    "op": ">",
    "value": 2
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 5000000000
   }
  ]
 },
 {
  "slug": "safe-stocks-to-buy",
  "name": "Safe Stocks To Buy",
  "cat": "Risk & Volatility",
  "desc": "Low-beta, low-debt large caps with solid returns.",
  "q": "Beta < 1 AND Beta > 0 AND Debt to Equity < 0.5 AND ROE > 12 AND Market Cap > 10000",
  "conditions": [
   {
    "metric": "beta",
    "op": "<",
    "value": 1
   },
   {
    "metric": "beta",
    "op": ">",
    "value": 0
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 0.5
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 12
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 10000000000
   }
  ]
 },
 {
  "slug": "ai-stocks-to-buy",
  "name": "AI Stocks To Buy",
  "cat": "Sector & Thematic",
  "desc": "Fast-growing, high-margin technology — where AI leaders cluster.",
  "q": "Sector = Technology AND Sales growth > 20 AND Gross Margin > 50 AND Market Cap > 5000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Technology"
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 20
   },
   {
    "metric": "grossMargin",
    "op": ">",
    "value": 50
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 5000000000
   }
  ]
 },
 {
  "slug": "semiconductor-stocks",
  "name": "Semiconductor Stocks",
  "cat": "Sector & Thematic",
  "desc": "Large tech with the chip-maker margin profile.",
  "q": "Sector = Technology AND Gross Margin > 40 AND Net Margin > 15 AND Market Cap > 10000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Technology"
   },
   {
    "metric": "grossMargin",
    "op": ">",
    "value": 40
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 15
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 10000000000
   }
  ]
 },
 {
  "slug": "ev-stocks",
  "name": "EV Stocks",
  "cat": "Sector & Thematic",
  "desc": "Fast-growing consumer cyclical names, including auto makers.",
  "q": "Sector = Consumer Cyclical AND Sales growth > 15 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Consumer Cyclical"
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "tech-stocks-to-buy",
  "name": "Tech Stocks To Buy",
  "cat": "Sector & Thematic",
  "desc": "Profitable, growing technology companies.",
  "q": "Sector = Technology AND ROE > 15 AND Sales growth > 10 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Technology"
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 15
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 10
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "energy-stocks",
  "name": "Energy Stocks",
  "cat": "Sector & Thematic",
  "desc": "The full US energy sector above $1B.",
  "q": "Sector = Energy AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Energy"
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "healthcare-stocks-to-buy",
  "name": "Healthcare Stocks To Buy",
  "cat": "Sector & Thematic",
  "desc": "Profitable healthcare companies with real margins.",
  "q": "Sector = Healthcare AND ROE > 12 AND Net Margin > 8 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Healthcare"
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 12
   },
   {
    "metric": "netMargin",
    "op": ">",
    "value": 8
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "bank-stocks",
  "name": "Bank Stocks",
  "cat": "Sector & Thematic",
  "desc": "Financial services companies above $2B.",
  "q": "Sector = Financial Services AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Financial Services"
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "cybersecurity-stocks",
  "name": "Cybersecurity Stocks",
  "cat": "Sector & Thematic",
  "desc": "Software-style economics: 60%+ gross margins and growing sales.",
  "q": "Sector = Technology AND Gross Margin > 60 AND Sales growth > 12",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Technology"
   },
   {
    "metric": "grossMargin",
    "op": ">",
    "value": 60
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 12
   }
  ]
 },
 {
  "slug": "clean-energy-stocks",
  "name": "Clean Energy Stocks",
  "cat": "Sector & Thematic",
  "desc": "Utilities — including renewable and clean-power operators.",
  "q": "Sector = Utilities AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Utilities"
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "quantum-computing-stocks",
  "name": "Quantum Computing Stocks",
  "cat": "Sector & Thematic",
  "desc": "Speculative small-to-mid tech growers.",
  "q": "Sector = Technology AND Market Cap > 500 AND Market Cap < 20000 AND Sales growth > 15",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Technology"
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 500000000
   },
   {
    "metric": "marketCap",
    "op": "<",
    "value": 20000000000
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 15
   }
  ]
 },
 {
  "slug": "stock-screener-starter",
  "name": "Stock Screener Starter",
  "cat": "Starter Screens",
  "desc": "A sensible first screen: large, reasonably priced, profitable.",
  "q": "Market Cap > 10000 AND P/E < 30 AND ROE > 15",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 10000000000
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 30
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 15
   }
  ]
 },
 {
  "slug": "free-stock-screener-picks",
  "name": "Free Stock Screener Picks",
  "cat": "Starter Screens",
  "desc": "Mid-to-large caps at fair multiples with solid returns.",
  "q": "Market Cap > 2000 AND P/E > 0 AND P/E < 20 AND ROE > 12",
  "conditions": [
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   },
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 20
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 12
   }
  ]
 },
 {
  "slug": "best-stock-screener-combo",
  "name": "Best Stock Screener Combo",
  "cat": "Starter Screens",
  "desc": "Growth, quality, and valuation in one balanced filter.",
  "q": "ROE > 15 AND Sales growth > 10 AND Debt to Equity < 1 AND P/E < 25 AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "roe",
    "op": ">",
    "value": 15
   },
   {
    "metric": "salesGrowth",
    "op": ">",
    "value": 10
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 1
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 25
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "nasdaq-style-tech-screen",
  "name": "NASDAQ Style Tech Screen",
  "cat": "Starter Screens",
  "desc": "Tech-heavy universe in the NASDAQ spirit.",
  "q": "Sector = Technology AND Market Cap > 1000",
  "conditions": [
   {
    "metric": "sector",
    "op": "=",
    "value": "Technology"
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 1000000000
   }
  ]
 },
 {
  "slug": "stocks-to-buy-now",
  "name": "Stocks To Buy Now",
  "cat": "Starter Screens",
  "desc": "Quality names moving up with earnings momentum.",
  "q": "Change % > 0 AND ROE > 15 AND YOY Qtr profit growth > 10 AND P/E < 25 AND Market Cap > 2000",
  "conditions": [
   {
    "metric": "changePct",
    "op": ">",
    "value": 0
   },
   {
    "metric": "roe",
    "op": ">",
    "value": 15
   },
   {
    "metric": "yoyQuarterlyProfitGrowth",
    "op": ">",
    "value": 10
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 25
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 2000000000
   }
  ]
 },
 {
  "slug": "best-stocks-to-buy-right-now",
  "name": "Best Stocks To Buy Right Now",
  "cat": "Starter Screens",
  "desc": "Strong returns, growing profits, sane price.",
  "q": "ROE > 18 AND Profit growth > 15 AND Debt to Equity < 1 AND P/E < 30 AND Market Cap > 5000",
  "conditions": [
   {
    "metric": "roe",
    "op": ">",
    "value": 18
   },
   {
    "metric": "profitGrowth",
    "op": ">",
    "value": 15
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 1
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 30
   },
   {
    "metric": "marketCap",
    "op": ">",
    "value": 5000000000
   }
  ]
 },
 {
  "slug": "how-to-find-undervalued-stocks",
  "name": "How To Find Undervalued Stocks",
  "cat": "Starter Screens",
  "desc": "The classic undervaluation checklist in one screen.",
  "q": "P/E > 0 AND P/E < 15 AND P/B < 2 AND Earnings yield > 6 AND Debt to Equity < 1",
  "conditions": [
   {
    "metric": "pe",
    "op": ">",
    "value": 0
   },
   {
    "metric": "pe",
    "op": "<",
    "value": 15
   },
   {
    "metric": "pb",
    "op": "<",
    "value": 2
   },
   {
    "metric": "earningsYield",
    "op": ">",
    "value": 6
   },
   {
    "metric": "debtToEquity",
    "op": "<",
    "value": 1
   }
  ]
 }
]

export const METRICS_SSR = {
 "market capitalization": {
  "key": "marketCap",
  "string": false
 },
 "market cap": {
  "key": "marketCap",
  "string": false
 },
 "price to earning": {
  "key": "pe",
  "string": false
 },
 "price to earnings": {
  "key": "pe",
  "string": false
 },
 "p e ratio": {
  "key": "pe",
  "string": false
 },
 "p e": {
  "key": "pe",
  "string": false
 },
 "price to book": {
  "key": "pb",
  "string": false
 },
 "price to book value": {
  "key": "pb",
  "string": false
 },
 "p b": {
  "key": "pb",
  "string": false
 },
 "price to sales": {
  "key": "ps",
  "string": false
 },
 "p s": {
  "key": "ps",
  "string": false
 },
 "return on equity": {
  "key": "roe",
  "string": false
 },
 "roe": {
  "key": "roe",
  "string": false
 },
 "return on assets": {
  "key": "roa",
  "string": false
 },
 "roa": {
  "key": "roa",
  "string": false
 },
 "return on capital employed": {
  "key": "roce",
  "string": false
 },
 "roce": {
  "key": "roce",
  "string": false
 },
 "net profit margin": {
  "key": "netMargin",
  "string": false
 },
 "net margin": {
  "key": "netMargin",
  "string": false
 },
 "dividend yield": {
  "key": "dividendYield",
  "string": false
 },
 "debt to equity": {
  "key": "debtToEquity",
  "string": false
 },
 "current price": {
  "key": "price",
  "string": false
 },
 "price": {
  "key": "price",
  "string": false
 },
 "sales": {
  "key": "sales",
  "string": false
 },
 "opm": {
  "key": "opm",
  "string": false
 },
 "operating profit margin": {
  "key": "opm",
  "string": false
 },
 "profit after tax": {
  "key": "profitAfterTax",
  "string": false
 },
 "pat": {
  "key": "profitAfterTax",
  "string": false
 },
 "sales latest quarter": {
  "key": "salesLatestQuarter",
  "string": false
 },
 "pat latest quarter": {
  "key": "profitAfterTaxLatestQuarter",
  "string": false
 },
 "profit after tax latest quarter": {
  "key": "profitAfterTaxLatestQuarter",
  "string": false
 },
 "yoy qtr sales growth": {
  "key": "yoyQuarterlySalesGrowth",
  "string": false
 },
 "yoy qtr profit growth": {
  "key": "yoyQuarterlyProfitGrowth",
  "string": false
 },
 "eps": {
  "key": "eps",
  "string": false
 },
 "debt": {
  "key": "debt",
  "string": false
 },
 "earnings yield": {
  "key": "earningsYield",
  "string": false
 },
 "sales growth": {
  "key": "salesGrowth",
  "string": false
 },
 "profit growth": {
  "key": "profitGrowth",
  "string": false
 },
 "price to free cash flow": {
  "key": "priceToFreeCashFlow",
  "string": false
 },
 "ev ebitda": {
  "key": "evEbitda",
  "string": false
 },
 "ev revenue": {
  "key": "evRevenue",
  "string": false
 },
 "enterprise value": {
  "key": "enterpriseValue",
  "string": false
 },
 "current ratio": {
  "key": "currentRatio",
  "string": false
 },
 "quick ratio": {
  "key": "quickRatio",
  "string": false
 },
 "cash ratio": {
  "key": "cashRatio",
  "string": false
 },
 "gross margin": {
  "key": "grossMargin",
  "string": false
 },
 "interest coverage ratio": {
  "key": "interestCoverage",
  "string": false
 },
 "peg ratio": {
  "key": "peg",
  "string": false
 },
 "sales growth 3years": {
  "key": "salesGrowth3y",
  "string": false
 },
 "sales growth 5years": {
  "key": "salesGrowth5y",
  "string": false
 },
 "profit growth 3years": {
  "key": "profitGrowth3y",
  "string": false
 },
 "profit growth 5years": {
  "key": "profitGrowth5y",
  "string": false
 },
 "average roe 3years": {
  "key": "avgRoe3y",
  "string": false
 },
 "average roe 5years": {
  "key": "avgRoe5y",
  "string": false
 },
 "change": {
  "key": "changePct",
  "string": false
 },
 "volume": {
  "key": "volume",
  "string": false
 },
 "average volume": {
  "key": "avgVolume",
  "string": false
 },
 "52 week high": {
  "key": "yearHigh",
  "string": false
 },
 "52 week low": {
  "key": "yearLow",
  "string": false
 },
 "beta": {
  "key": "beta",
  "string": false
 },
 "operating margin": {
  "key": "opMargin",
  "string": false
 },
 "ev sales": {
  "key": "evSales",
  "string": false
 },
 "p fcf": {
  "key": "pFcf",
  "string": false
 },
 "p ocf": {
  "key": "pOcf",
  "string": false
 },
 "interest coverage": {
  "key": "interestCoverage",
  "string": false
 },
 "payout ratio": {
  "key": "payoutRatio",
  "string": false
 },
 "book value per share": {
  "key": "bookValuePs",
  "string": false
 },
 "ebitda": {
  "key": "ebitda",
  "string": false
 },
 "free cash flow": {
  "key": "freeCashFlow",
  "string": false
 },
 "operating cash flow": {
  "key": "operatingCashFlow",
  "string": false
 },
 "total debt": {
  "key": "totalDebt",
  "string": false
 },
 "total cash": {
  "key": "totalCash",
  "string": false
 },
 "net debt": {
  "key": "netDebt",
  "string": false
 },
 "sector": {
  "key": "sector",
  "string": true
 },
 "country": {
  "key": "country",
  "string": true
 }
}

export function parseQuerySSR(q) {
  const norm = v => String(v || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
  const conditions = []
  for (const part of String(q || '').split(/\s+AND\s+/i)) {
    const m = part.trim().match(/^(.+?)\s*(>=|<=|>|<|=)\s*(.+)$/)
    if (!m) continue
    const entry = METRICS_SSR[norm(m[1])]
    if (!entry) continue
    let value = m[3].trim()
    if (!entry.string) {
      value = Number(value.replace(/[$,%]/g, ''))
      if (!Number.isFinite(value)) continue
      if (entry.key === 'marketCap') value = value * 1e6
    } else {
      value = value.replace(/^["']|["']$/g, '').trim()
      if (!value) continue
    }
    conditions.push({ metric: entry.key, op: m[2], value })
  }
  return conditions
}
